[workspace]
authors = ["natapol2547 <robloxplay41@gmail.com>"]
channels = ["https://prefix.dev/robostack-jazzy", "https://prefix.dev/conda-forge"]
name = "walkie-agent-ros"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]

[feature.docs.tasks]
docs = "mkdocs serve"
docs-build = "mkdocs build --strict"

[feature.docs.dependencies]
mkdocs-material = ">=9.7,<10"
mkdocs = ">=1.6,<2"

[environments]
docs = { features = ["docs"], no-default-feature = true }
